name: earthdaily-processor
channels:
 - conda-forge
 - defaults
dependencies:
  - python=3.10.12
  - ipykernel
  - python-dotenv>=0.5.1
  - geojson
  - pyproj
  - zarr
  - pip 
  - pip:
    # aws
    - boto3
    # azure
    - azure-storage-blob
    - geosyspy
    - earthdaily==0.0.1rc4
    - jupyter
    - matplotlib
    - numpy 
    - scipy
    - geogif
