name: stackfox-processor
channels:
 - conda-forge
 - defaults
dependencies:
  - python=3.10
  - ipykernel
# external requirements
  - click
  - Sphinx
  - coverage
  - awscli>=1.27.130
  - flake8
  - python-dotenv>=0.5.1
  - requests
  - requests-mock
  - scipy
  - pandas
  - geojson
  - shapely
  - rasterio
  - xarray
  - pyproj
  - matplotlib 
  - zarr
  - numpy
  - gdal
  - pandas
  - geopandas
  - pystac-client
  - requests
  - matplotlib
  - xarray
  - rioxarray
  - h5netcdf 
  - netcdf4
  - pystac
  - stackstac
  - odc-stac
  - pip:
    - fastapi
    - hypercorn[trio]==0.14.3
    # aws
    - boto3
    # azure
    - azure-storage-blob
    - geosyspy