name: earthdaily-processor
channels:
 - conda-forge
 - defaults
dependencies:
  - python=3.10.12
  - ipykernel
  - click
  - Sphinx
  - coverage
  - awscli>=1.27.130
  - flake8
  - python-dotenv>=0.5.1
  - requests
  - requests-mock
  - scipy
  - pandas
  - geojson
  - shapely
  - rasterio
  - pyproj
  - matplotlib 
  - zarr
  - numpy
  - gdal
  - pandas
  - geopandas
  - matplotlib
  - xarray
  - rioxarray
  - netcdf4
  - pip:
    # aws
    - boto3
    # azure
    - azure-storage-blob
    - geosyspy
    - earthdaily