name: earthdaily-processor
channels:
 - conda-forge
 - defaults
dependencies:
  - python=3.10.12
  - ipykernel
  - python-dotenv>=0.5.1
  - pandas
  - geojson
  - shapely
  - rasterio
  - pyproj
  - zarr
  - gdal
  - geopandas
  - xarray
  - rioxarray
  - pip 
  - pip:
    # aws
    - boto3
    # azure
    - azure-storage-blob
    - geosyspy
    - earthdaily
    - jupyter
    - matplotlib
    - numpy 
    - scipy